version: 1
repository:
  enabled: false
sandbox:
  image:
    ref: index.docker.io/library/docker@sha256:aa3df78ecf320f5fafdce71c659f1629e96e9de0968305fe1de670e0ca9176ce
  docker:
    required: true
  network:
    default: deny
    allow:
      - host: auth.docker.io
        ports: [443]
      - host: registry-1.docker.io
        ports: [443]
      - host: production.cloudflare.docker.com
        ports: [443]
      - host: docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com
        ports: [443]
