env:
  MISE_YES: "1"
  MISE_TRUSTED_CONFIG_PATHS: /buildkite/builds

steps:
  - label: ":test_tube: Test (Linux)"
    command: mise run test
    cache:
      paths:
        - "~/.local/share/mise"
        - "~/.cache/mise"
        - "~/.local/state/mise"
      size: "20g"
      name: "mise-cache"
    agents:
      queue: hosted

  - label: ":test_tube: Test (macOS)"
    command: mise run test
    cache:
      paths:
        - "~/.local/share/mise"
        - "~/.cache/mise"
        - "~/.local/state/mise"
      size: "20g"
      name: "mise-cache"
    agents:
      queue: mac-small

  - label: ":fire: E2E (Firecracker)"
    command: scripts/ci-cleanroom-e2e.sh
    agents:
      queue: cleanroom
