cache:
  paths:
    - "~/.local/share/mise"
    - "~/.cache/mise"
    - "~/.local/state/mise"
  size: "20g"
  name: "mise-cache"

env:
  MISE_YES: "1"
  MISE_TRUSTED_CONFIG_PATHS: /buildkite/builds

steps:
  - label: ":linux: Build (Linux)"
    command: mise run build
    agents:
      queue: hosted

  - label: ":test_tube: Test (Linux)"
    command: mise run test
    agents:
      queue: hosted

  - label: ":mac: Build (macOS)"
    command: mise run build
    agents:
      queue: mac-small

  - label: ":test_tube: Test (macOS)"
    command: mise run test
    agents:
      queue: mac-small

  - label: ":fire: E2E (Firecracker)"
    command: scripts/ci-cleanroom-e2e.sh
    agents:
      queue: cleanroom
