package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"github.com/buildkite/cleanroom/internal/exposure"
)

type DNSCommand struct {
	Action string `arg:"" required:"" help:"DNS action (install, uninstall, status)"`
	JSON   bool   `help:"Print DNS status as JSON (status action only)"`
}

type dnsStatusPayload struct {
	Supported       bool   `json:"supported"`
	Installed       bool   `json:"installed"`
	Managed         bool   `json:"managed"`
	Trusted         bool   `json:"trusted"`
	Path            string `json:"path"`
	Domain          string `json:"domain"`
	Listen          string `json:"listen"`
	CertificatePath string `json:"certificate_path,omitempty"`
	TrustMessage    string `json:"trust_message,omitempty"`
	Message         string `json:"message,omitempty"`
}

const dnsResolverManagedMarker = "Generated by cleanroom"

var (
	dnsInstallGOOS         = runtime.GOOS
	dnsInstallEUID         = os.Geteuid
	dnsInstallMkdirAll     = os.MkdirAll
	dnsInstallLstat        = os.Lstat
	dnsInstallReadFile     = os.ReadFile
	dnsInstallWriteFile    = os.WriteFile
	dnsInstallRemoveFile   = os.Remove
	dnsInstallRunCommand   = runDNSInstallCommand
	dnsInstallLookupUser   = user.Lookup
	dnsInstallChown        = os.Lchown
	dnsInstallGetenv       = os.Getenv
	dnsInstallUserHomeDir  = os.UserHomeDir
	dnsResolverInstallPath = filepath.Join("/etc", "resolver", exposure.Domain)
)

func (c *DNSCommand) Run(ctx *runtimeContext) error {
	action := strings.TrimSpace(strings.ToLower(c.Action))
	if c.JSON && action != "status" {
		return errors.New("--json is only supported with dns status")
	}

	switch action {
	case "install":
		return c.installDNS(ctx)
	case "uninstall":
		return c.uninstallDNS(ctx)
	case "status":
		return c.dnsStatus(ctx)
	default:
		return fmt.Errorf("unsupported dns action %q", c.Action)
	}
}

func (c *DNSCommand) installDNS(ctx *runtimeContext) error {
	if dnsInstallGOOS != "darwin" {
		return fmt.Errorf("dns install is unsupported on %s (expected darwin)", dnsInstallGOOS)
	}
	if dnsInstallEUID() != 0 {
		return errors.New("dns install requires root privileges (use sudo cleanroom dns install)")
	}

	content, listen, err := resolverFileContent(exposure.DefaultDNSListen)
	if err != nil {
		return err
	}
	path := dnsResolverInstallPath
	if existing, err := dnsInstallReadFile(path); err == nil {
		if !resolverFileManaged(existing) {
			return fmt.Errorf("resolver file %s already exists and is not managed by cleanroom", path)
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read resolver file %s: %w", path, err)
	}

	tlsDir, err := dnsExposureTLSDir()
	if err != nil {
		return err
	}
	certPath := filepath.Join(tlsDir, exposure.LocalCertificateFilename)
	if _, err := dnsInstallReadRegularFile(certPath); err == nil {
		if err := removeExposureCertificateTrust(certPath); err != nil {
			return err
		}
	} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read exposure certificate %s: %w", certPath, err)
	}
	parentDirs := exposureTLSParentDirsToChown(tlsDir)
	cert, err := exposure.EnsureLocalCertificate(exposure.Domain, tlsDir)
	if err != nil {
		return fmt.Errorf("ensure exposure certificate: %w", err)
	}
	if err := chownExposureTLSMaterial(tlsDir, parentDirs); err != nil {
		return err
	}
	if err := installExposureCertificateTrust(cert.CertPath); err != nil {
		return err
	}

	if err := dnsInstallMkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create resolver directory %s: %w", filepath.Dir(path), err)
	}
	if err := dnsInstallWriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write resolver file %s: %w", path, err)
	}

	_, err = fmt.Fprint(ctx.Stdout, renderSummaryBlock(summaryBlock{
		Title:      "dns installed",
		TitleStyle: defaultTerminalPalette().info,
		Fields: []startupField{
			{Key: "domain", Value: exposure.Domain},
			{Key: "resolver", Value: path},
			{Key: "listen", Value: listen},
			{Key: "certificate", Value: cert.CertPath},
			{Key: "trusted", Value: "true"},
		},
	}, shouldUseANSI(ctx.Stdout)))
	return err
}

func (c *DNSCommand) uninstallDNS(ctx *runtimeContext) error {
	if dnsInstallGOOS != "darwin" {
		return fmt.Errorf("dns uninstall is unsupported on %s (expected darwin)", dnsInstallGOOS)
	}
	if dnsInstallEUID() != 0 {
		return errors.New("dns uninstall requires root privileges (use sudo cleanroom dns uninstall)")
	}

	path := dnsResolverInstallPath
	existing, err := dnsInstallReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		if err := uninstallExposureCertificateTrustAndFiles(); err != nil {
			return err
		}
		return writeDNSStatusSummary(ctx, dnsStatusPayload{
			Supported: true,
			Installed: false,
			Managed:   false,
			Path:      path,
			Domain:    exposure.Domain,
			Listen:    exposure.DefaultDNSListen,
			Message:   "dns already uninstalled",
		})
	}
	if err != nil {
		return fmt.Errorf("read resolver file %s: %w", path, err)
	}
	if !resolverFileManaged(existing) {
		return fmt.Errorf("resolver file %s is not managed by cleanroom", path)
	}
	if err := uninstallExposureCertificateTrustAndFiles(); err != nil {
		return err
	}
	if err := dnsInstallRemoveFile(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("remove resolver file %s: %w", path, err)
	}

	return writeDNSStatusSummary(ctx, dnsStatusPayload{
		Supported: true,
		Installed: false,
		Managed:   true,
		Path:      path,
		Domain:    exposure.Domain,
		Listen:    exposure.DefaultDNSListen,
		Message:   "dns uninstalled",
	})
}

func (c *DNSCommand) dnsStatus(ctx *runtimeContext) error {
	status := c.currentDNSStatus()
	if c.JSON {
		enc := json.NewEncoder(ctx.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(status)
	}
	return writeDNSStatusSummary(ctx, status)
}

func (c *DNSCommand) currentDNSStatus() dnsStatusPayload {
	listen := exposure.DefaultDNSListen
	status := dnsStatusPayload{
		Supported: dnsInstallGOOS == "darwin",
		Path:      dnsResolverInstallPath,
		Domain:    exposure.Domain,
		Listen:    listen,
	}
	if tlsDir, err := dnsExposureTLSDir(); err == nil {
		status.CertificatePath = filepath.Join(tlsDir, exposure.LocalCertificateFilename)
	}
	if !status.Supported {
		status.Message = "dns resolver install is unsupported on this platform"
		return status
	}
	if strings.TrimSpace(status.CertificatePath) != "" {
		trusted, trustMessage := exposureCertificateTrustStatus(status.CertificatePath)
		status.Trusted = trusted
		status.TrustMessage = trustMessage
	}

	data, err := dnsInstallReadFile(dnsResolverInstallPath)
	switch {
	case err == nil:
		status.Installed = true
		status.Managed = resolverFileManaged(data)
		if status.Managed {
			status.Listen = resolverFileListen(data, listen)
			status.Message = "dns installed"
		} else {
			status.Message = "resolver file exists but is not managed by cleanroom"
		}
	case errors.Is(err, fs.ErrNotExist):
		status.Message = "dns not installed"
	default:
		status.Message = fmt.Sprintf("read resolver file: %v", err)
	}
	return status
}

func writeDNSStatusSummary(ctx *runtimeContext, status dnsStatusPayload) error {
	title := status.Message
	if strings.TrimSpace(title) == "" {
		title = "dns status"
	}
	titleStyle := defaultTerminalPalette().info
	if !status.Installed || !status.Managed || !status.Supported {
		titleStyle = defaultTerminalPalette().warn
	}
	_, err := fmt.Fprint(ctx.Stdout, renderSummaryBlock(summaryBlock{
		Title:      title,
		TitleStyle: titleStyle,
		Fields: []startupField{
			{Key: "domain", Value: status.Domain},
			{Key: "resolver", Value: status.Path},
			{Key: "listen", Value: status.Listen},
			{Key: "certificate", Value: status.CertificatePath},
			{Key: "trusted", Value: strconv.FormatBool(status.Trusted)},
			{Key: "trust_status", Value: status.TrustMessage},
		},
	}, shouldUseANSI(ctx.Stdout)))
	return err
}

func resolverFileContent(listen string) (string, string, error) {
	if strings.TrimSpace(listen) == "" {
		listen = exposure.DefaultDNSListen
	}
	host, port, err := net.SplitHostPort(listen)
	if err != nil {
		return "", "", fmt.Errorf("invalid dns listen address %q: %w", listen, err)
	}
	host = strings.Trim(host, "[]")
	if host == "" {
		host = "127.0.0.1"
	}
	if net.ParseIP(host) == nil {
		return "", "", fmt.Errorf("invalid dns listen address %q: resolver nameserver must be an IP address", listen)
	}
	portNumber, err := strconv.Atoi(port)
	if err != nil || portNumber < 1 || portNumber > 65535 {
		return "", "", fmt.Errorf("invalid dns listen address %q: port must be 1-65535", listen)
	}
	return fmt.Sprintf("# %s. Do not edit.\nnameserver %s\nport %d\n", dnsResolverManagedMarker, host, portNumber), net.JoinHostPort(host, strconv.Itoa(portNumber)), nil
}

func resolverFileManaged(data []byte) bool {
	return strings.Contains(string(data), dnsResolverManagedMarker)
}

func resolverFileListen(data []byte, fallback string) string {
	var host, port string
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		switch fields[0] {
		case "nameserver":
			host = strings.Trim(fields[1], "[]")
		case "port":
			port = fields[1]
		}
	}
	if net.ParseIP(host) == nil {
		return fallback
	}
	portNumber, err := strconv.Atoi(port)
	if err != nil || portNumber < 1 || portNumber > 65535 {
		return fallback
	}
	return net.JoinHostPort(host, strconv.Itoa(portNumber))
}

func dnsExposureTLSDir() (string, error) {
	if configHome := strings.TrimSpace(dnsInstallGetenv("XDG_CONFIG_HOME")); configHome != "" {
		return filepath.Join(configHome, "cleanroom", "tls"), nil
	}
	if home := dnsExposureInvokingHomeDir(); home != "" {
		return filepath.Join(home, ".config", "cleanroom", "tls"), nil
	}
	return exposure.DefaultTLSDir()
}

func dnsExposureInvokingHomeDir() string {
	sudoUser := strings.TrimSpace(dnsInstallGetenv("SUDO_USER"))
	if sudoUser == "" || sudoUser == "root" {
		return ""
	}
	u, err := dnsInstallLookupUser(sudoUser)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(u.HomeDir)
}

func exposureTLSParentDirsToChown(dir string) []string {
	dir = filepath.Clean(strings.TrimSpace(dir))
	if dir == "" || dir == "." {
		return nil
	}
	userHome := dnsExposureInvokingHomeDir()
	parents := []string{filepath.Dir(filepath.Dir(dir)), filepath.Dir(dir)}
	dirs := make([]string, 0, len(parents))
	seen := make(map[string]struct{}, len(parents))
	for _, path := range parents {
		path = filepath.Clean(path)
		if path == "" || path == "." || path == string(filepath.Separator) || path == dir {
			continue
		}
		if _, ok := seen[path]; ok {
			continue
		}
		seen[path] = struct{}{}
		if pathWithinDir(userHome, path) {
			dirs = append(dirs, path)
			continue
		}
		if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
			dirs = append(dirs, path)
		}
	}
	return dirs
}

func pathWithinDir(base, path string) bool {
	base = filepath.Clean(strings.TrimSpace(base))
	path = filepath.Clean(strings.TrimSpace(path))
	if base == "" || base == "." || base == string(filepath.Separator) || path == "" {
		return false
	}
	rel, err := filepath.Rel(base, path)
	if err != nil {
		return false
	}
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)))
}

func chownExposureTLSMaterial(dir string, parentDirs []string) error {
	uidRaw := strings.TrimSpace(dnsInstallGetenv("SUDO_UID"))
	gidRaw := strings.TrimSpace(dnsInstallGetenv("SUDO_GID"))
	if uidRaw == "" || gidRaw == "" {
		return nil
	}
	uid, err := strconv.Atoi(uidRaw)
	if err != nil {
		return fmt.Errorf("parse SUDO_UID: %w", err)
	}
	gid, err := strconv.Atoi(gidRaw)
	if err != nil {
		return fmt.Errorf("parse SUDO_GID: %w", err)
	}
	paths := append([]string(nil), parentDirs...)
	paths = append(paths,
		dir,
		filepath.Join(dir, exposure.LocalCertificateFilename),
		filepath.Join(dir, exposure.LocalCertificateKeyFilename),
	)
	symlinkRoot := dnsExposureTLSSymlinkRoot()
	for _, path := range paths {
		if err := rejectDNSInstallSymlinkPath(path, symlinkRoot); err != nil {
			return fmt.Errorf("chown %s: %w", path, err)
		}
		if err := dnsInstallChown(path, uid, gid); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("chown %s: %w", path, err)
		}
	}
	return nil
}

func installExposureCertificateTrust(certPath string) error {
	keychain, err := exposureTrustKeychainPath()
	if err != nil {
		return err
	}
	if err := runExposureTrustSecurity("add-trusted-cert", "-r", "trustRoot", "-p", "ssl", "-k", keychain, certPath); err != nil {
		if strings.Contains(err.Error(), "already exists") {
			return nil
		}
		return fmt.Errorf("trust exposure certificate %s: %w", certPath, err)
	}
	return nil
}

func removeExposureCertificateTrust(certPath string) error {
	if err := runExposureTrustSecurity("remove-trusted-cert", certPath); err != nil {
		msg := strings.ToLower(err.Error())
		if strings.Contains(msg, "could not be found") || strings.Contains(msg, "not found") {
			return nil
		}
		return fmt.Errorf("remove exposure certificate trust %s: %w", certPath, err)
	}
	return nil
}

func uninstallExposureCertificateTrustAndFiles() error {
	tlsDir, err := dnsExposureTLSDir()
	if err != nil {
		return err
	}
	certPath := filepath.Join(tlsDir, exposure.LocalCertificateFilename)
	if _, err := dnsInstallReadRegularFile(certPath); err == nil {
		if err := removeExposureCertificateTrust(certPath); err != nil {
			return err
		}
	} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read exposure certificate %s: %w", certPath, err)
	}
	return exposure.RemoveLocalCertificateFiles(tlsDir)
}

func exposureCertificateTrustStatus(certPath string) (bool, string) {
	if _, err := dnsInstallReadRegularFile(certPath); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, "certificate not found"
		}
		return false, fmt.Sprintf("read certificate: %v", err)
	}
	keychain, err := exposureTrustKeychainPath()
	if err != nil {
		return false, err.Error()
	}
	if err := runExposureTrustSecurity("verify-cert", "-c", certPath, "-p", "ssl", "-L", "-l", "-k", keychain); err != nil {
		return false, err.Error()
	}
	return true, "trusted"
}

func dnsInstallReadRegularFile(path string) ([]byte, error) {
	if err := rejectDNSInstallSymlinkPath(path, dnsExposureTLSSymlinkRoot()); err != nil {
		return nil, err
	}
	info, err := dnsInstallLstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("%s is not a regular file", path)
	}
	return dnsInstallReadRegularFileMatchingInfo(path, info)
}

func dnsInstallReadRegularFileMatchingInfo(path string, info os.FileInfo) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	openedInfo, err := f.Stat()
	if err != nil {
		return nil, err
	}
	if !os.SameFile(info, openedInfo) {
		return nil, fmt.Errorf("%s changed while opening", path)
	}
	return io.ReadAll(f)
}

func dnsExposureTLSSymlinkRoot() string {
	if configHome := strings.TrimSpace(dnsInstallGetenv("XDG_CONFIG_HOME")); configHome != "" {
		configHome = filepath.Clean(configHome)
		if home := dnsExposureInvokingHomeDir(); home != "" && pathWithinDir(home, configHome) {
			return filepath.Clean(home)
		}
		return configHome
	}
	if home := dnsExposureInvokingHomeDir(); home != "" {
		return filepath.Clean(home)
	}
	return ""
}

func rejectDNSInstallSymlinkPath(path, root string) error {
	path = filepath.Clean(path)
	root = filepath.Clean(strings.TrimSpace(root))
	if path == "" || path == "." {
		return nil
	}
	if root == "" || root == "." || !pathWithinDir(root, path) {
		return rejectDNSInstallSymlinkLeaf(path)
	}
	if err := rejectDNSInstallSymlinkLeaf(root); err != nil {
		return err
	}
	rel, err := filepath.Rel(root, path)
	if err != nil || rel == "." {
		return nil
	}
	current := root
	for _, elem := range strings.Split(rel, string(filepath.Separator)) {
		if elem == "" || elem == "." {
			continue
		}
		current = filepath.Join(current, elem)
		if err := rejectDNSInstallSymlinkLeaf(current); err != nil {
			return err
		}
	}
	return nil
}

func rejectDNSInstallSymlinkLeaf(path string) error {
	info, err := dnsInstallLstat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%s is a symbolic link", path)
	}
	return nil
}

func exposureTrustKeychainPath() (string, error) {
	_, home, err := exposureTrustUser()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "Library", "Keychains", "login.keychain-db"), nil
}

func runExposureTrustSecurity(args ...string) error {
	userName, _, err := exposureTrustUser()
	if err != nil {
		return err
	}
	if userName == "" {
		return dnsInstallRunCommand("security", args...)
	}
	sudoArgs := append([]string{"-u", userName, "security"}, args...)
	return dnsInstallRunCommand("sudo", sudoArgs...)
}

func exposureTrustUser() (string, string, error) {
	sudoUser := strings.TrimSpace(dnsInstallGetenv("SUDO_USER"))
	if sudoUser != "" && sudoUser != "root" {
		u, err := dnsInstallLookupUser(sudoUser)
		if err != nil {
			return "", "", fmt.Errorf("lookup sudo user %q: %w", sudoUser, err)
		}
		home := strings.TrimSpace(u.HomeDir)
		if home == "" {
			return "", "", fmt.Errorf("lookup sudo user %q: missing home directory", sudoUser)
		}
		return sudoUser, home, nil
	}
	home, err := dnsInstallUserHomeDir()
	if err != nil {
		return "", "", fmt.Errorf("resolve user home directory for exposure certificate trust: %w", err)
	}
	if strings.TrimSpace(home) == "" {
		return "", "", errors.New("resolve user home directory for exposure certificate trust: empty home directory")
	}
	return "", home, nil
}

func runDNSInstallCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err == nil {
		return nil
	}
	detail := strings.TrimSpace(string(output))
	if detail == "" {
		return err
	}
	return fmt.Errorf("%w: %s", err, detail)
}
