package cli

import (
	"crypto/x509"
	"encoding/pem"
	"os"
	"os/user"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/buildkite/cleanroom/internal/exposure"
)

func TestResolverFileContent(t *testing.T) {
	t.Parallel()

	content, listen, err := resolverFileContent("127.0.0.1:1153")
	if err != nil {
		t.Fatalf("resolverFileContent returned error: %v", err)
	}
	if got, want := listen, "127.0.0.1:1153"; got != want {
		t.Fatalf("unexpected listen: got %q want %q", got, want)
	}
	for _, want := range []string{
		"# Generated by cleanroom. Do not edit.",
		"nameserver 127.0.0.1",
		"port 1153",
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("expected resolver content to contain %q, got %q", want, content)
		}
	}
	if !resolverFileManaged([]byte(content)) {
		t.Fatal("expected generated resolver file to be managed")
	}
}

func TestResolverFileContentRejectsNonIPNameserver(t *testing.T) {
	t.Parallel()

	_, _, err := resolverFileContent("localhost:1153")
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "nameserver must be an IP address") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestDNSInstallTrustsLeafCertificateInInvokingUserKeychain(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)
	var chownPaths []string
	dnsInstallChown = func(path string, _, _ int) error {
		chownPaths = append(chownPaths, path)
		return nil
	}

	stdout, _ := makeStdoutCapture(t)
	cmd := &DNSCommand{Action: "install"}
	if err := cmd.Run(&runtimeContext{Stdout: stdout}); err != nil {
		t.Fatalf("DNSCommand.Run returned error: %v", err)
	}

	certPath := filepath.Join(home, ".config", "cleanroom", "tls", exposure.LocalCertificateFilename)
	keychain := filepath.Join(home, "Library", "Keychains", "login.keychain-db")
	wantCalls := [][]string{{
		"sudo", "-u", "lachlan", "security", "add-trusted-cert",
		"-r", "trustRoot",
		"-p", "ssl",
		"-k", keychain,
		certPath,
	}}
	if !reflect.DeepEqual(calls, wantCalls) {
		t.Fatalf("unexpected trust commands: got %v want %v", calls, wantCalls)
	}

	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatalf("read generated certificate: %v", err)
	}
	block, _ := pemDecodeCertificate(certPEM)
	cert, err := x509.ParseCertificate(block)
	if err != nil {
		t.Fatalf("parse generated certificate: %v", err)
	}
	if cert.IsCA {
		t.Fatal("expected generated exposure certificate not to be a CA")
	}
	if err := cert.VerifyHostname("buildkite." + exposure.Domain); err != nil {
		t.Fatalf("expected generated certificate to verify exposure hostname: %v", err)
	}
	if strings.Contains(strings.Join(calls[0], " "), "System.keychain") {
		t.Fatalf("did not expect install to trust the system keychain: %v", calls[0])
	}

	wantChownPaths := []string{
		filepath.Join(home, ".config"),
		filepath.Join(home, ".config", "cleanroom"),
		filepath.Join(home, ".config", "cleanroom", "tls"),
		certPath,
		filepath.Join(home, ".config", "cleanroom", "tls", exposure.LocalCertificateKeyFilename),
	}
	if !reflect.DeepEqual(chownPaths, wantChownPaths) {
		t.Fatalf("unexpected chown paths: got %v want %v", chownPaths, wantChownPaths)
	}
}

func TestDNSInstallRejectsUnmanagedResolverBeforeTrust(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)
	if err := os.MkdirAll(filepath.Dir(resolverPath), 0o755); err != nil {
		t.Fatalf("mkdir resolver dir: %v", err)
	}
	if err := os.WriteFile(resolverPath, []byte("nameserver 127.0.0.1\n"), 0o644); err != nil {
		t.Fatalf("write resolver file: %v", err)
	}

	stdout, _ := makeStdoutCapture(t)
	cmd := &DNSCommand{Action: "install"}
	err := cmd.Run(&runtimeContext{Stdout: stdout})
	if err == nil {
		t.Fatal("expected unmanaged resolver error")
	}
	if !strings.Contains(err.Error(), "not managed by cleanroom") {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(calls) != 0 {
		t.Fatalf("expected no trust commands before resolver ownership check, got %v", calls)
	}
}

func TestDNSInstallRefreshesExistingCertificateTrust(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)
	tlsDir := filepath.Join(home, ".config", "cleanroom", "tls")
	cert, err := exposure.EnsureLocalCertificate(exposure.Domain, tlsDir)
	if err != nil {
		t.Fatalf("EnsureLocalCertificate returned error: %v", err)
	}

	stdout, _ := makeStdoutCapture(t)
	cmd := &DNSCommand{Action: "install"}
	if err := cmd.Run(&runtimeContext{Stdout: stdout}); err != nil {
		t.Fatalf("DNSCommand.Run returned error: %v", err)
	}

	keychain := filepath.Join(home, "Library", "Keychains", "login.keychain-db")
	wantCalls := [][]string{
		{"sudo", "-u", "lachlan", "security", "remove-trusted-cert", cert.CertPath},
		{
			"sudo", "-u", "lachlan", "security", "add-trusted-cert",
			"-r", "trustRoot",
			"-p", "ssl",
			"-k", keychain,
			cert.CertPath,
		},
	}
	if !reflect.DeepEqual(calls, wantCalls) {
		t.Fatalf("unexpected trust refresh commands: got %v want %v", calls, wantCalls)
	}
}

func TestDNSStatusReportsCertificateTrust(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)

	content, _, err := resolverFileContent("127.0.0.1:1153")
	if err != nil {
		t.Fatalf("resolverFileContent returned error: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(resolverPath), 0o755); err != nil {
		t.Fatalf("mkdir resolver dir: %v", err)
	}
	if err := os.WriteFile(resolverPath, []byte(content), 0o644); err != nil {
		t.Fatalf("write resolver file: %v", err)
	}
	tlsDir := filepath.Join(home, ".config", "cleanroom", "tls")
	cert, err := exposure.EnsureLocalCertificate(exposure.Domain, tlsDir)
	if err != nil {
		t.Fatalf("EnsureLocalCertificate returned error: %v", err)
	}

	status := (&DNSCommand{}).currentDNSStatus()
	if !status.Installed || !status.Managed {
		t.Fatalf("expected managed resolver status, got %+v", status)
	}
	if got, want := status.Listen, "127.0.0.1:1153"; got != want {
		t.Fatalf("expected status listen from resolver file: got %q want %q", got, want)
	}
	if !status.Trusted {
		t.Fatalf("expected trusted certificate status, got %+v", status)
	}
	if got, want := status.CertificatePath, cert.CertPath; got != want {
		t.Fatalf("unexpected certificate path: got %q want %q", got, want)
	}

	keychain := filepath.Join(home, "Library", "Keychains", "login.keychain-db")
	wantCalls := [][]string{{
		"sudo", "-u", "lachlan", "security", "verify-cert",
		"-c", cert.CertPath,
		"-p", "ssl",
		"-n", "buildkite." + exposure.Domain,
		"-L",
		"-k", keychain,
	}}
	if !reflect.DeepEqual(calls, wantCalls) {
		t.Fatalf("unexpected trust status commands: got %v want %v", calls, wantCalls)
	}
}

func TestDNSUninstallRemovesCertificateTrustAndFiles(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)

	content, _, err := resolverFileContent("127.0.0.1:1153")
	if err != nil {
		t.Fatalf("resolverFileContent returned error: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(resolverPath), 0o755); err != nil {
		t.Fatalf("mkdir resolver dir: %v", err)
	}
	if err := os.WriteFile(resolverPath, []byte(content), 0o644); err != nil {
		t.Fatalf("write resolver file: %v", err)
	}
	tlsDir := filepath.Join(home, ".config", "cleanroom", "tls")
	cert, err := exposure.EnsureLocalCertificate(exposure.Domain, tlsDir)
	if err != nil {
		t.Fatalf("EnsureLocalCertificate returned error: %v", err)
	}

	stdout, _ := makeStdoutCapture(t)
	cmd := &DNSCommand{Action: "uninstall"}
	if err := cmd.Run(&runtimeContext{Stdout: stdout}); err != nil {
		t.Fatalf("DNSCommand.Run returned error: %v", err)
	}

	wantCalls := [][]string{{
		"sudo", "-u", "lachlan", "security", "remove-trusted-cert", cert.CertPath,
	}}
	if !reflect.DeepEqual(calls, wantCalls) {
		t.Fatalf("unexpected trust removal commands: got %v want %v", calls, wantCalls)
	}
	if _, err := os.Stat(resolverPath); !os.IsNotExist(err) {
		t.Fatalf("expected resolver file to be removed, got err=%v", err)
	}
	if _, err := os.Stat(cert.CertPath); !os.IsNotExist(err) {
		t.Fatalf("expected certificate file to be removed, got err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(tlsDir, exposure.LocalCertificateKeyFilename)); !os.IsNotExist(err) {
		t.Fatalf("expected certificate key file to be removed, got err=%v", err)
	}
}

func TestDNSUninstallRemovesCertificateTrustWhenResolverMissing(t *testing.T) {
	home := t.TempDir()
	resolverPath := filepath.Join(t.TempDir(), "resolver", exposure.Domain)
	var calls [][]string
	stubDNSInstallEnvironment(t, home, resolverPath, &calls)
	tlsDir := filepath.Join(home, ".config", "cleanroom", "tls")
	cert, err := exposure.EnsureLocalCertificate(exposure.Domain, tlsDir)
	if err != nil {
		t.Fatalf("EnsureLocalCertificate returned error: %v", err)
	}

	stdout, readStdout := makeStdoutCapture(t)
	cmd := &DNSCommand{Action: "uninstall"}
	if err := cmd.Run(&runtimeContext{Stdout: stdout}); err != nil {
		t.Fatalf("DNSCommand.Run returned error: %v", err)
	}

	wantCalls := [][]string{{
		"sudo", "-u", "lachlan", "security", "remove-trusted-cert", cert.CertPath,
	}}
	if !reflect.DeepEqual(calls, wantCalls) {
		t.Fatalf("unexpected trust removal commands: got %v want %v", calls, wantCalls)
	}
	if _, err := os.Stat(cert.CertPath); !os.IsNotExist(err) {
		t.Fatalf("expected certificate file to be removed, got err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(tlsDir, exposure.LocalCertificateKeyFilename)); !os.IsNotExist(err) {
		t.Fatalf("expected certificate key file to be removed, got err=%v", err)
	}
	if out := readStdout(); !strings.Contains(out, "dns already uninstalled") {
		t.Fatalf("expected already-uninstalled message, got: %s", out)
	}
}

func stubDNSInstallEnvironment(t *testing.T, home, resolverPath string, calls *[][]string) {
	t.Helper()
	prevGOOS := dnsInstallGOOS
	prevEUID := dnsInstallEUID
	prevRunCommand := dnsInstallRunCommand
	prevLookupUser := dnsInstallLookupUser
	prevChown := dnsInstallChown
	prevGetenv := dnsInstallGetenv
	prevUserHomeDir := dnsInstallUserHomeDir
	prevResolverInstallPath := dnsResolverInstallPath
	dnsInstallGOOS = "darwin"
	dnsInstallEUID = func() int { return 0 }
	dnsInstallRunCommand = func(name string, args ...string) error {
		*calls = append(*calls, append([]string{name}, args...))
		return nil
	}
	dnsInstallLookupUser = func(name string) (*user.User, error) {
		return &user.User{Username: name, HomeDir: home}, nil
	}
	dnsInstallChown = func(string, int, int) error {
		return nil
	}
	dnsInstallGetenv = func(key string) string {
		switch key {
		case "SUDO_USER":
			return "lachlan"
		case "SUDO_UID":
			return "501"
		case "SUDO_GID":
			return "20"
		default:
			return ""
		}
	}
	dnsInstallUserHomeDir = func() (string, error) {
		return home, nil
	}
	dnsResolverInstallPath = resolverPath
	t.Cleanup(func() {
		dnsInstallGOOS = prevGOOS
		dnsInstallEUID = prevEUID
		dnsInstallRunCommand = prevRunCommand
		dnsInstallLookupUser = prevLookupUser
		dnsInstallChown = prevChown
		dnsInstallGetenv = prevGetenv
		dnsInstallUserHomeDir = prevUserHomeDir
		dnsResolverInstallPath = prevResolverInstallPath
	})
}

func pemDecodeCertificate(data []byte) ([]byte, bool) {
	block, _ := pem.Decode(data)
	if block == nil || block.Type != "CERTIFICATE" {
		return nil, false
	}
	return block.Bytes, true
}
