name: Cleanroom
options:
  minimumXcodeGenVersion: 2.44.1
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.10
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  Cleanroom:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: main.swift
      - path: NetworkFilterDaemon.swift
    dependencies:
      - sdk: AppKit.framework
      - sdk: NetworkExtension.framework
      - sdk: SystemExtensions.framework
      - target: CleanroomFilterDataProvider
        embed: true
        codeSign: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.buildkite.cleanroom.network
        PRODUCT_NAME: Cleanroom
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: entitlements.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
  CleanroomFilterDataProvider:
    type: system-extension
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: NetworkFilterDaemon.swift
      - path: CleanroomFilterDataProvider/main.swift
      - path: CleanroomFilterDataProvider/provider.swift
    dependencies:
      - sdk: NetworkExtension.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.buildkite.cleanroom.network.filter
        PRODUCT_NAME: CleanroomFilterDataProvider
        INFOPLIST_FILE: CleanroomFilterDataProvider/Info.plist
        CODE_SIGN_ENTITLEMENTS: CleanroomFilterDataProvider/entitlements.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        OTHER_LDFLAGS:
          - -lbsm
